apiVersion: v1
kind: Service
metadata:
  name: portfoliowebsite
  namespace: portfoliowebsite
spec:
  type: ClusterIP
  selector:
    app: portfoliowebsite
  ports:
    - port: 80
      targetPort: 80
